# Generated by Django 3.1.3 on 2021-02-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kataBuka', models.TextField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('harga', models.IntegerField()),
            ],
        ),
    ]
