# Generated by Django 3.1.3 on 2021-02-21 09:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0004_auto_20210221_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harga',
            name='kataBuka',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
