# Generated by Django 3.1.3 on 2021-02-21 20:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0005_auto_20210221_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kataBuka', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('judul', models.CharField(max_length=200)),
                ('isi', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_wa', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Metode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kataBuka', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='')),
                ('judul', models.CharField(max_length=200)),
                ('isi', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelayanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kataBuka', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('judul', models.CharField(max_length=200)),
                ('judul2', models.CharField(max_length=200)),
                ('judul3', models.CharField(max_length=200)),
                ('judul4', models.CharField(max_length=200)),
                ('isi', ckeditor.fields.RichTextField(blank=True)),
                ('isi2', ckeditor.fields.RichTextField(blank=True)),
                ('isi3', ckeditor.fields.RichTextField(blank=True)),
                ('isi4', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
