# Generated by Django 3.1.3 on 2021-02-22 13:28

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0006_faq_kontak_metode_pelayanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='kontak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halaman.harga'),
        ),
        migrations.AddField(
            model_name='harga',
            name='pelayanan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halaman.pelayanan'),
        ),
        migrations.AddField(
            model_name='kontak',
            name='kataBuka',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metode',
            name='kontak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halaman.kontak'),
        ),
    ]
