# Generated by Django 3.1.3 on 2021-02-22 18:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0007_auto_20210222_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='kataBuka',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
