# Generated by Django 3.1.3 on 2021-02-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0008_gallery_katabuka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
