# Generated by Django 3.1.3 on 2021-02-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halaman', '0009_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harga',
            name='harga',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
